name: tilseg_2024_mac
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - appdirs=1.4.4
  - appnope=0.1.4
  - astroid=2.14.2
  - asttokens=2.4.1
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.2.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cryptography=42.0.2
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask-core=2023.11.0
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - dill=0.3.7
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.10.0
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - icu=73.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.3
  - ipython=8.22.1
  - isort=5.9.3
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.6.0
  - lazy_loader=0.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.5.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.0
  - openslide=3.4.1
  - openslide-python=1.3.1
  - openssl=3.2.1
  - packaging=23.1
  - pandas=2.1.4
  - parso=0.8.3
  - partd=1.4.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pylint=2.16.2
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pywavelets=1.5.0
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - readline=8.2
  - requests=2.31.0
  - scikit-image=0.22.0
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tifffile=2023.4.12
  - tk=8.6.12
  - tomlkit=0.11.1
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.1
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - wrapt=1.14.1
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - filelock==3.13.1
      - gdown==5.1.0
      - iniconfig==2.0.0
      - joblib==1.3.2
      - opencv-python==4.9.0.80
      - pluggy==1.4.0
      - scipy==1.12.0
      - soupsieve==2.5
      - threadpoolctl==3.3.0
      - tomli==2.0.1
      - uuid==1.30
