name: tilseg
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - numpy=1.22.3
  - opencv=4.6.0
  - openslide=3.4.1
  - openslide-python=1.1.2
  - pandas=1.5.2
  - pillow=9.3.0
  - pip=22.3.1
  - pytest=7.2.1
  - python=3.10.9
  - scikit-image=0.19.3
  - scikit-learn=1.2.1
  - scipy=1.7.3
  - seaborn=0.12.2

